### ISSUE TITLE
3rd RandomForest test fails sometimes (esp. during CI) 

### ISSUE THREAD

**Issue by LSBOSS** [kalimdorjs/kalimdorjs#126]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
From time to time the 3rd test of RandomForest implemented in test/ensemble/forest.test.ts fails. This ultimately results in a failed build when used in a CI context. 

See **Other information** below for log output

* **Other information**

 FAIL  test/ensemble/forest.test.ts
  ensemble:forest
    RandomForest
      ✓ should return a result of X1 and y1 with random state 1 (9ms)
      ✓ should return a result of X1 and y1 with random state 2 (4ms)
      ✕ should train test split and predict correct test #1 (334ms)
  ● ensemble:forest › RandomForest › should train test split and predict correct test #1
    expect(received).toBeGreaterThanOrEqual(expected)
    
    Expected value to be greater than or equal:
      0.7
    Received:
      0.631578947368421
      44 |       const shouldBeGreater = 0.7;
      45 |       const accuracy = accuracyScore({ y_true: yTest, y_pred: yPred });
    > 46 |       expect(accuracy).toBeGreaterThanOrEqual(shouldBeGreater);
      47 |     });
      48 |   });
      49 | });
      
      at Object.<anonymous> (test/ensemble/forest.test.ts:46:24)
      at step (test/ensemble/forest.test.ts:32:23)
      at Object.next (test/ensemble/forest.test.ts:13:51)
      at fulfilled (test/ensemble/forest.test.ts:4:56)

**Comment by JasonShin** [comment]
@LSBOSS Thanks for this, I think I can have a look at it soon. We need to set a random state to the RF classifier before running the tests.
